FROM microsoft/dotnet:1.1.0-sdk-projectjson
COPY . /app
WORKDIR /app
 
RUN ["dotnet", "restore", "--source", "https://api.nuget.org/v3/index.json", "--source", "https://www.myget.org/F/warden/api/v3/index.json", "--source", "https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json", "--no-cache"]
RUN ["dotnet", "build"]
 
EXPOSE 5054/tcp
ENV ASPNETCORE_URLS http://*:5054
ENV ASPNETCORE_ENVIRONMENT local
 
ENTRYPOINT ["dotnet", "run"]